OBTENER COMPARACION PARAMETROS VS UNIDADES DE MEDIDA

In [5]:
import pandas as pd
import openpyxl
import os



directory_path = r'G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYuXbB3Pj0UXueIKJ\09. Contrato CS115 EIA 2024\03.WIP\03.Hidroquímica\2. Actualizacion BDD\2. Nuevo - Mauro\1. Certificados\1. Revision final'


# Crear un DataFrame vacío para almacenar los datos de los archivos Excel
data_parametros = pd.DataFrame()
data_compared = pd.DataFrame()

data_compared_1 = pd.DataFrame()

excel_files = [file for file in os.listdir(directory_path) if file.endswith(('.xlsx'))]

# Procesar cada archivo Excel encontrado
for file in excel_files:
    file_path = os.path.join(directory_path, file)  # Construir la ruta completa al archivo
    xls = pd.ExcelFile(file_path)
    wb = openpyxl.load_workbook(file_path)

    for hoja_archivo in xls.sheet_names:
        hoja = wb[hoja_archivo]
        rango = hoja['C133:AZ133']

        ultima_celda_con_datos = None
        for celda in rango[0]:
            if celda.value is not None:
                ultima_celda_con_datos = celda

        if ultima_celda_con_datos:
            columna = ''.join(filter(str.isalpha, ultima_celda_con_datos.coordinate))
            print(f'La última columna con datos es >>> {columna} <<< , en la hoja: >>> {hoja_archivo} <<<')
            
    
            data_df = pd.read_excel(xls, sheet_name= hoja_archivo, skiprows=141, nrows=120, usecols=f"B:{columna}", header= None)  
            data_df.reset_index(drop=False)
            data_compared_1 = pd.DataFrame()
            data_compared_1 = data_df[[1, 2]].copy()

            data_compared_1['Ruta'] = file_path
            data_compared_1['Hoja'] = hoja_archivo
            data_compared_1['Archivo'] = file
            data_compared_1.columns = ['Parametros', 'Unidad_medida', 'Ruta', 'Hoja', 'Archivo']
            
            data_df.drop(data_df.columns[1], axis=1, inplace=True)
            
           
            
            # data_pivoted = data_df.T
            

            # # PARAMETROS COMO COLUMNAS
            # new_header = data_pivoted.iloc[0]  
            # data_pivoted = data_pivoted[1:]  
            # data_pivoted.columns = new_header

            # # data_parametros.reset_index(drop=True, inplace=True)
            # # data_pivoted.reset_index(drop=True, inplace=True)
            # data_pivoted.reset_index(drop=True, inplace=True)

            # # data_identificacion total
            # data_parametros = pd.concat([data_parametros, data_pivoted], ignore_index=True)
            # # data_parametros = pd.concat([data_parametros, data_df], ignore_index=True)
            # for column in data_parametros.columns:
            #     data_parametros[column] = pd.to_numeric(data_parametros[column], errors='coerce')
            #data_parametros = data_parametros.apply(pd.to_numeric, errors='coerce')
            data_compared = pd.concat([data_compared, data_compared_1], ignore_index=True)
        else:
            print(f'No hay datos en el rango C133:AZ133, para la hoja: {hoja_archivo}')
            
         
# data_parametros
data_compared

La última columna con datos es >>> G <<< , en la hoja: >>> 2017 <<<
La última columna con datos es >>> J <<< , en la hoja: >>> 2018 <<<
La última columna con datos es >>> I <<< , en la hoja: >>> (2019) <<<
La última columna con datos es >>> G <<< , en la hoja: >>> (2020) <<<
La última columna con datos es >>> H <<< , en la hoja: >>> (2021) <<<
La última columna con datos es >>> N <<< , en la hoja: >>> (2022) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> (2023) <<<
La última columna con datos es >>> G <<< , en la hoja: >>> (2024) <<<
No hay datos en el rango C133:AZ133, para la hoja: terr
No hay datos en el rango C133:AZ133, para la hoja: lab
La última columna con datos es >>> AC <<< , en la hoja: >>> Cámara recolectora (2020) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> Cámara recolectora (2022) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> Cámara recolectora (2021) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> Cámara recolectora (2023) <<<
La última columna con datos es >>> L <<< , en la hoja: >>> Dren Mauro (2022) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> Dren Mauro (2023) <<<
La última columna con datos es >>> F <<< , en la hoja: >>> Dren Mauro (2024) <<<
La última columna con datos es >>> AC <<< , en la hoja: >>> DPDM 2012  <<<
La última columna con datos es >>> R <<< , en la hoja: >>> DPDM 2013 <<<
La última columna con datos es >>> V <<< , en la hoja: >>> DPDM 2014 <<<
La última columna con datos es >>> O <<< , en la hoja: >>> DPDM 2015 <<<
La última columna con datos es >>> O <<< , en la hoja: >>> DPDM 2016 <<<
La última columna con datos es >>> N <<< , en la hoja: >>> DPDM 2017 <<<
La última columna con datos es >>> O <<< , en la hoja: >>> DPDM 2018 <<<
La última columna con datos es >>> Q <<< , en la hoja: >>> DPDM (2019) <<<
La última columna con datos es >>> Q <<< , en la hoja: >>> DPDM (2020) <<<
La última columna con datos es >>> Q <<< , en la hoja: >>> DPDM (2021) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> DPDM (2022) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> DPDM (2023) <<<
La última columna con datos es >>> G <<< , en la hoja: >>> DPDM (2024) <<<
La última columna con datos es >>> F <<< , en la hoja: >>> ATM 2008 <<<
La última columna con datos es >>> M <<< , en la hoja: >>> ATM (2011) <<<
La última columna con datos es >>> Z <<< , en la hoja: >>> ATM (2012) <<<
La última columna con datos es >>> AB <<< , en la hoja: >>>  ATM (2013) <<<
La última columna con datos es >>> V <<< , en la hoja: >>>  ATM (2014) <<<
La última columna con datos es >>> O <<< , en la hoja: >>>  ATM (2015) <<<
La última columna con datos es >>> O <<< , en la hoja: >>>  ATM (2016) <<<
La última columna con datos es >>> O <<< , en la hoja: >>>  ATM (2017) <<<
La última columna con datos es >>> O <<< , en la hoja: >>>  ATM (2018) <<<
La última columna con datos es >>> O <<< , en la hoja: >>>  ATM (2019) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> ATM (2020) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> ATM (2021) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> ATM (2022) <<<
La última columna con datos es >>> O <<< , en la hoja: >>> ATM (2023) <<<
La última columna con datos es >>> F <<< , en la hoja: >>> ATM (2024) <<<

,Parametros,Unidad_medida,Ruta,Hoja,Archivo
0,"2,4_D_µg/L",NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,2017,Sentina Dren Mauro_MM_MM.xlsx
1,Aceites_y_Grasas_mg/L,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,2017,Sentina Dren Mauro_MM_MM.xlsx
2,Alcalinidad_Carbonatos_(Laboratorio)_CaCO3_mg/L,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,2017,Sentina Dren Mauro_MM_MM.xlsx
3,Alcalinidad_Total_CaCO3_mg/L,mg/L,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,2017,Sentina Dren Mauro_MM_MM.xlsx
4,Aluminio_Total_mg/L,mg/L,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,2017,Sentina Dren Mauro_MM_MM.xlsx
...,...,...,...,...,...
5155,Clorofila_A_mg/L,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,ATM (2024),ATM_(Aguas Claras Tranque Mauro)_VV_VV_MM.xlsx
5156,Detergente_mg/L,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,ATM (2024),ATM_(Aguas Claras Tranque Mauro)_VV_VV_MM.xlsx
5157,Cumplimiento,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,ATM (2024),ATM_(Aguas Claras Tranque Mauro)_VV_VV_MM.xlsx
5158,Alcalinidad Bicarbonato (Laboratorio)_mg CaCO3/L,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,ATM (2024),ATM_(Aguas Claras Tranque Mauro)_VV_VV_MM.xlsx
5159,tipo_dato,NaN,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,ATM (2024),ATM_(Aguas Claras Tranque Mauro)_VV_VV_MM.xlsx

In [8]:
data_compared.to_excel('MAURO_comparacion_unidad_07-06-2024.xlsx', sheet_name='Comparacion_U_Medida', index=False)

CONECCION A LA BD

In [97]:
import psycopg2
from sqlalchemy import create_engine

# Credenciales db
host = 'localhost'
database = 'certificados_dbo'
username = 'postgres'  
password = '1234' 

# Crea la coneccion
conn = psycopg2.connect(
    host=host,
    database=database,
    user=username,
    password=password
)

engine = create_engine('postgresql://'+username+':'+password+'@'+host+'/'+database)
table_name = 'comparacion_unidades_medida'

df_data_bd = pd.read_sql_table(table_name, con=engine)#Trae la tabla de la bda un dataframe

df_data_bd

,Parametros,Unidad_medida,Ruta,Hoja,Archivo
0,QAQC_Numero_muestreo,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
1,"2,4_D_µg/L",None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
2,Aceites_y_Grasas_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
3,Alcalinidad_Carbonatos_(Laboratorio)_CaCO3_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
4,Alcalinidad_Total_CaCO3_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
...,...,...,...,...,...
61273,Nitrógeno_Total_Kjeldahl_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,CA-3 (2023),5.62 CA-3 Antes Depósito Quebrada NW (EX Botad...
61274,Poder_Espumógeno_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,CA-3 (2023),5.62 CA-3 Antes Depósito Quebrada NW (EX Botad...
61275,Sulfuros_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,CA-3 (2023),5.62 CA-3 Antes Depósito Quebrada NW (EX Botad...
61276,Turbidez_(Campo)_NTU,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,CA-3 (2023),5.62 CA-3 Antes Depósito Quebrada NW (EX Botad...
61277,Altura Limnimétrica_m,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,CA-3 (2023),5.62 CA-3 Antes Depósito Quebrada NW (EX Botad...

UNIMOS DATA DE LA BD A LA NUEVA DATA

In [98]:
df_update = pd.concat([df_data_bd, data_compared], ignore_index=True)

SUBIMOS A LA BD LA DATA YA UNIDA

In [99]:
# df_update = data_compared
df_update.to_sql(table_name, engine, index=False, if_exists='replace',)

522

REVISAMOS DATA EXISTENTE

In [101]:
df_data_bd = pd.read_sql_table(table_name, con=engine)#Trae la tabla de la bda un dataframe

df_data_bd

,Parametros,Unidad_medida,Ruta,Hoja,Archivo
0,QAQC_Numero_muestreo,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
1,"2,4_D_µg/L",None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
2,Aceites_y_Grasas_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
3,Alcalinidad_Carbonatos_(Laboratorio)_CaCO3_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
4,Alcalinidad_Total_CaCO3_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,RCH-3(2018),RCH-3_VV_VV.xlsx
...,...,...,...,...,...
68517,Nitrógeno_Total_Kjeldahl_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,5 ABQ-7E (2023),5 ABQ-7(E)_MM_CIGF_MM_PC.xlsx
68518,Poder_Espumógeno_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,5 ABQ-7E (2023),5 ABQ-7(E)_MM_CIGF_MM_PC.xlsx
68519,Sulfuros_mg/L,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,5 ABQ-7E (2023),5 ABQ-7(E)_MM_CIGF_MM_PC.xlsx
68520,Turbidez_(Campo)_NTU,NTU,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,5 ABQ-7E (2023),5 ABQ-7(E)_MM_CIGF_MM_PC.xlsx
68521,Altura Limnimétrica_m,None,G:\.shortcut-targets-by-id\1ugEph6zRyoKHbwpiYu...,5 ABQ-7E (2023),5 ABQ-7(E)_MM_CIGF_MM_PC.xlsx